mvc-project-camp/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace mvc_project_camp.Controllers
{
	public class AdminCategoryController : Controller
	{
		CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
		public IActionResult Index()
		{
			var categoryValues = categoryManager.GetList();
			return View(categoryValues);
		}
		[HttpGet]
        public IActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
		public IActionResult AddCategory(Category category)
		{
			CategoryValidator categoryValidator = new CategoryValidator();
			ValidationResult results = categoryValidator.Validate(category);
			if(results.IsValid) 
			{ 
				categoryManager.CategoryAdd(category);
				return RedirectToAction("Index");
			}
			else
			{
				foreach(var item in results.Errors)
				{
					ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
				}
			}
			return View();
		}
		public IActionResult DeleteCategory(int id)
		{
			var categoryValue = categoryManager.GetById(id);
			categoryManager.CategoryDelete(categoryValue);
			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult EditCategory(int id)
		{
            var categoryValue = categoryManager.GetById(id);
			return View(categoryValue);
        }

		[HttpPost]
		public IActionResult EditCategory(Category category)
		{
			categoryManager.CategoryUpdate(category);
			return RedirectToAction("Index");
		}
	}
}

mvc-project-camp/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
	ViewData["Title"] = "AddCategory";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
	<div class="form-group">
		@Html.Label("Kategori Adı")
		@Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
		@Html.ValidationMessageFor(x => x.CategoryName)
		<br /> <br />
		@Html.Label("Açıklamayı yazınız")
		@Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
		@Html.ValidationMessageFor(x => x.CategoryDescription)
		<br /> <br />
		<button class="btn btn-info">Kaydet</button>
	</div>
}

mvc-project-camp/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category


@{
	ViewData["Title"] = "EditCategory";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h1>Kategori Güncelleme Sayfası</h1>
@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
	<div class="form-group">
		@Html.Label("Kategori Id")
		@Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
		<br />
		@Html.Label("Kategori Adı")
		@Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
		<br />
		@Html.Label("Kategori Açıklaması")
		@Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
		<br />
		<button class="btn btn-success">Güncelle</button>
	</div>
}

mvc-project-camp/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
    }
</table>
<br />
<a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>